public class BeveragesWindow extends javax.swing.JFrame{

    /**
     * Creates new form beverages
     */
    public BeveragesWindow() {
        initComponents();
        fizzydrinkslist.setSelectedIndex(0);
        waterlist.setSelectedIndex(0);
        milkshakeslist.setSelectedIndex(0);
        juiceslist.setSelectedIndex(0);
        sizelist.setSelectedIndex(2);
        sizelist1.setSelectedIndex(2);
        sizelist2.setSelectedIndex(2);
        sizelist3.setSelectedIndex(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addtocart = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cart = new javax.swing.JButton();
        burger = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        fizzydrinks = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        milkshake = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        juice = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        juice2 = new javax.swing.JLabel();
        fizzydrinkslist = new javax.swing.JComboBox<>();
        milkshakeslist = new javax.swing.JComboBox<>();
        juiceslist = new javax.swing.JComboBox<>();
        waterlist = new javax.swing.JComboBox<>();
        addtocart1 = new javax.swing.JButton();
        addtocart2 = new javax.swing.JButton();
        addtocart3 = new javax.swing.JButton();
        sizelist = new javax.swing.JComboBox<>();
        sizelist1 = new javax.swing.JComboBox<>();
        sizelist2 = new javax.swing.JComboBox<>();
        sizelist3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 51, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BEVERAGES");

        addtocart.setBackground(new java.awt.Color(51, 51, 51));
        addtocart.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addtocart.setForeground(new java.awt.Color(255, 255, 255));
        addtocart.setText("Add to Cart");
        addtocart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Fries");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cart.setBackground(new java.awt.Color(153, 153, 153));
        cart.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cart.setForeground(new java.awt.Color(255, 255, 255));
        cart.setText("Cart");
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });

        burger.setBackground(new java.awt.Color(153, 153, 153));
        burger.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        burger.setForeground(new java.awt.Color(255, 255, 255));
        burger.setText("Burger");
        burger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burgerActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        fizzydrinks.setBackground(new java.awt.Color(0, 0, 153));
        fizzydrinks.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fizzydrinks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fizzydrinks.setText("Fizzy Drinks \n" + "(Rs. " + Prices.fizzyDrink + ")");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fizzydrinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fizzydrinks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(51, 204, 255));

        milkshake.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        milkshake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        milkshake.setText("Milkshakes (Rs. " + Prices.milkshakeDrink + ")");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(milkshake, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(milkshake, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 204, 255));

        juice.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        juice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        juice.setText("Juices (Rs. " + Prices.juiceDrink + ")");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(juice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(juice, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 204, 255));

        juice2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        juice2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        juice2.setText("Water (Rs. " + Prices.waterDrink +")");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(juice2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(juice2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
        );

        fizzydrinkslist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Pepsi","7Up","Miranda","Mountain Dew"}));
        fizzydrinkslist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fizzydrinkslistActionPerformed(evt);
            }
        });

        milkshakeslist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Strawberry","Banana","Chocolate","Vanilla"}));
        milkshakeslist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milkshakeslistActionPerformed(evt);
            }
        });

        juiceslist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Apple","Orange","Lemon"}));

        waterlist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Chilled", "Room Temprature"}));
        waterlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterlistActionPerformed(evt);
            }
        });

        addtocart1.setBackground(new java.awt.Color(51, 51, 51));
        addtocart1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addtocart1.setForeground(new java.awt.Color(255, 255, 255));
        addtocart1.setText("Add to Cart");
        addtocart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocart1ActionPerformed(evt);
            }
        });

        addtocart2.setBackground(new java.awt.Color(51, 51, 51));
        addtocart2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addtocart2.setForeground(new java.awt.Color(255, 255, 255));
        addtocart2.setText("Add to Cart");
        addtocart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocart2ActionPerformed(evt);
            }
        });

        addtocart3.setBackground(new java.awt.Color(51, 51, 51));
        addtocart3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addtocart3.setForeground(new java.awt.Color(255, 255, 255));
        addtocart3.setText("Add to Cart");
        addtocart3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocart3ActionPerformed(evt);
            }
        });

        sizelist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Large","Medium","Small"}));
        sizelist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizelistActionPerformed(evt);
            }
        });

        sizelist1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Large","Medium","Small"}));
        sizelist1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizelist1ActionPerformed(evt);
            }
        });

        sizelist2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Large","Medium","Small"}));
        sizelist2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizelist2ActionPerformed(evt);
            }
        });

        sizelist3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Large","Medium","Small"}));
        sizelist3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizelist3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fizzydrinkslist, 0, 167, Short.MAX_VALUE)
                                .addComponent(sizelist, javax.swing.GroupLayout.Alignment.LEADING, 0, 167, Short.MAX_VALUE))
                            .addComponent(addtocart2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(milkshakeslist, 0, 167, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addtocart3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sizelist1, 0, 167, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(juiceslist, 0, 167, Short.MAX_VALUE)
                            .addComponent(addtocart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sizelist2, 0, 167, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(waterlist, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addtocart1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sizelist3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(cart, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(burger, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cart, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(burger, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fizzydrinkslist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(milkshakeslist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(juiceslist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waterlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizelist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizelist1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizelist2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizelist3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addtocart2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addtocart, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(addtocart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addtocart3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void milkshakeslistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milkshakeslistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_milkshakeslistActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HomeWindow().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FriesWindow().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new CartWindow().setVisible(true);
    }//GEN-LAST:event_cartActionPerformed

    private void burgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burgerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new BurgerWindow().setVisible(true);
    }//GEN-LAST:event_burgerActionPerformed

    private void addtocartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartActionPerformed
        // TODO add your handling code here:
        String[] juiceflavours = {"Apple", "Orange", "Lemon"};
        String currentflavour = juiceflavours[juiceslist.getSelectedIndex()];
        Size[] sizes = {Size.LARGE, Size.MEDIUM, Size.SMALL};
        Size chosenSize = sizes[sizelist2.getSelectedIndex()];
        CurrentOrder.order.addDrink(new Juices(chosenSize, currentflavour));
        juiceslist.setSelectedIndex(0);
        sizelist2.setSelectedIndex(2);
    }//GEN-LAST:event_addtocartActionPerformed

    private void fizzydrinkslistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fizzydrinkslistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fizzydrinkslistActionPerformed

    private void addtocart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocart1ActionPerformed
        // TODO add your handling code here:
        String[] waterflavours = {"Chilled", "Room Temprature"};
        String currentflavour = waterflavours[waterlist.getSelectedIndex()];
        Size[] sizes = {Size.LARGE, Size.MEDIUM, Size.SMALL};
        Size chosenSize = sizes[sizelist3.getSelectedIndex()];
        CurrentOrder.order.addDrink(new Water(chosenSize, currentflavour));
        waterlist.setSelectedIndex(0);
        sizelist3.setSelectedIndex(2);
    }//GEN-LAST:event_addtocart1ActionPerformed

    private void addtocart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocart2ActionPerformed
        // TODO add your handling code here:
        String[] fizzyflavours = {"Pepsi", "7Up", "Miranda", "Mountain Dew"};
        String currentflavour = fizzyflavours[fizzydrinkslist.getSelectedIndex()];
        Size[] sizes = {Size.LARGE, Size.MEDIUM, Size.SMALL};
        Size chosenSize = sizes[sizelist.getSelectedIndex()];
        CurrentOrder.order.addDrink(new Fizzy(chosenSize, currentflavour));
        fizzydrinkslist.setSelectedIndex(0);
        sizelist.setSelectedIndex(2);
        
    }//GEN-LAST:event_addtocart2ActionPerformed

    private void waterlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterlistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waterlistActionPerformed

    private void addtocart3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocart3ActionPerformed
        // TODO add your handling code here:
        String[] mshakeflavours = {"Strawberry", "Banana", "Chocolate", "Vanilla"};
        String currentflavour = mshakeflavours[milkshakeslist.getSelectedIndex()];
        Size[] sizes = {Size.LARGE, Size.MEDIUM, Size.SMALL};
        Size chosenSize = sizes[sizelist1.getSelectedIndex()];
        CurrentOrder.order.addDrink(new Milkshake(chosenSize, currentflavour));
        milkshakeslist.setSelectedIndex(0);
        sizelist1.setSelectedIndex(2);
    }//GEN-LAST:event_addtocart3ActionPerformed

    private void sizelistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizelistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizelistActionPerformed

    private void sizelist1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizelist1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizelist1ActionPerformed

    private void sizelist2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizelist2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizelist2ActionPerformed

    private void sizelist3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizelist3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizelist3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeveragesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeveragesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeveragesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeveragesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeveragesWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addtocart;
    private javax.swing.JButton addtocart1;
    private javax.swing.JButton addtocart2;
    private javax.swing.JButton addtocart3;
    private javax.swing.JButton burger;
    private javax.swing.JButton cart;
    private javax.swing.JLabel fizzydrinks;
    private javax.swing.JComboBox<String> fizzydrinkslist;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel juice;
    private javax.swing.JLabel juice2;
    private javax.swing.JComboBox<String> juiceslist;
    private javax.swing.JLabel milkshake;
    private javax.swing.JComboBox<String> milkshakeslist;
    private javax.swing.JComboBox<String> sizelist;
    private javax.swing.JComboBox<String> sizelist1;
    private javax.swing.JComboBox<String> sizelist2;
    private javax.swing.JComboBox<String> sizelist3;
    private javax.swing.JComboBox<String> waterlist;
    // End of variables declaration//GEN-END:variables
}
